### ISSUE TITLE
Replication factor error

### ISSUE THREAD

**Issue by quartox** [dask/old-dask-yarn#13]
Looks like it is probably a `knit` error and may be specific to my system but I am getting a replication factor error.

Is there an interface for specifying hadoop or hive conf directory? I use an environment variable to specify a hive conf directory when using spark.

```
File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/dask_yarn/core.py", line 78, in start
    virtual_cores=cpus, memory=memory)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/knit/core.py", line 285, in start
    self.app_id = self.client.start(env, ','.join(files), app_name, queue)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/py4j/java_gateway.py", line 813, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/jlord/.conda/envs/dask/lib/python3.5/site-packages/py4j/protocol.py", line 308, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling t.start.
: org.apache.hadoop.ipc.RemoteException(java.io.IOException): Requested replication factor of 1 is less than the required minimum of 2 for /user/jlord/.knitDeps/knit-1.0-SNAPSHOT.jar
```

**Comment by quasiben** [comment]
@quartox, thanks for trying things out.  You're right, this is an issue with knit and while we could get replication info from conf settings we could do something similar to what spark does.

As the error indicates, the problem is with how knit is uploading the jar.  On the scala side we have hardcoded the [replication factor to 1](
https://github.com/dask/knit/blob/master/knit_jvm/src/main/scala/io/continuum/knit/Utils.scala#L82-L83).  The way spark handles this is with the config option: [spark.yarn.submit.file.replication](https://spark.apache.org/docs/latest/running-on-yarn.html) .  We could do the same thing with an arg in the `YARNCluster` object

**Comment by quasiben** [comment]
I think it will probably take me another night to fix but also happy to help anyone else step through the solution

**Comment by mrocklin** [comment]
@martindurant do you have any interest in diving into Yarn?

**Comment by martindurant** [comment]
Happy to help, if @quasiben , you want to pass things on to me.

**Comment by quasiben** [comment]
@martindurant I started a PR: https://github.com/dask/knit/pull/64 -- not totally sure it will work. Can you take that over and write tests for it ?
